### ISSUE TITLE
Give warning when trying to play sound in a format for which the feature is not enabled

### ISSUE THREAD

**Issue by bjorn3** [NiklasEi/bevy_kira_audio#15] opened 2021-06-23 16:53 UTC
Sound didn't work for someone on the bevy discord: https://discord.com/channels/691052431525675048/742884593551802431/857300358158352465 It turns out that the "wav" feature was not enabled. No warnings whatsoever were shown. It wasn't until I looked at the Cargo.toml that I found the problem.

**Comment by NiklasEi** [comment] 2021-06-23 17:53
Isn't that something that should happen in Bevy itself?
The asset server is responsible to load the `wav` file. If the `wav` feature is not enabled there will be no loader registered for the audio file.

As far as I remember I used to get logs from Bevy when I tried to load an asset that had no registered loader, but I just tested it with the audio example and could not reproduce. A very quick look into engine code suggests though that [a "missing loader" error](https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/src/asset_server.rs#L23) should [be logged](https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/src/asset_server.rs#L373). Maybe I am doing something wrong with my loaders here, or it is a Bevy issue?

Thank you for helping out on Discord!

**Comment by bjorn3** [comment] 2021-06-23 18:49
Could it be that the asset loader for bevy_audio gets used instead or bevy_kira_audio when the feature flag is disabled?

**Comment by NiklasEi** [comment] 2021-06-23 21:02
To use `bevy_kira_audio` the Bevy audio feature should not be selected. That's actually a very good point, I don't think I mentioned that explicitly in the readme.

The `wav` file should not be loaded by bevy though in this case. All `bevy_audio` asset loaders apart from the `mp3` loader are not enabled by default.

**Comment by NiklasEi** [comment] 2021-08-30 19:37
I'll close this for now as I don't think there is anything more I can do here. When a user tries to load an asset that the engine doesn't know a loader for, Bevy logs a warning.

That users of this crate should disable Bevy's `audio` feature is no documented.

**Closed by NiklasEi** 2021-08-30 19:37 UTC
